name: mo_jannah
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  go_router: ^13.2.0
  flutter_native_splash: 2.3.10
  flutter_spinkit: ^5.2.0
  flutter_svg: ^2.0.10+1
  animations: ^2.0.11
  intl_phone_field: ^3.2.0
  pin_code_fields: ^8.0.1
  google_maps_flutter: ^2.6.0
  flutter_polyline_points: ^2.0.0
  http: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter_native_splash:
  color: "#05F2AF"
  image: assets/images/logos/splash-logo.png
  android_12:
    color: "#05F2AF"
    image: assets/images/logos/splash-logo-android12.png

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/images/logos/
    - assets/images/icons/
    - assets/data/map_styles.json
